### PR TITLE
make the cola case a simple all operators recipe

### PR DESCRIPTION
**Pull request by dafnapension**

### CODE REVIEW

**Comment by yoavkatz** [comment]
Dafna, can you explain the motivation for this PR?\

Why is the cola card becoming complex and adding metric calcullation in the pre-process step?

I'm missing something basic.

**Review by yoavkatz — CHANGES_REQUESTED** [review]
Please see my questions, in the conversation.

**Comment by dafnapension** [comment]
> Dafna, can you explain the motivation for this PR?\
> 
> Why is the cola card becoming complex and adding metric calcullation in the pre-process step?
> 
> I'm missing something basic.

Hi @yoavkatz , I was missing something in what @elronbandel explained to me about this mission. So indeed @elronbandel transferred this PR to draft, and I started from scratch..

**Comment by dafnapension** [comment]
closing for now, a new one opened on this general subject instead, and also in the form of a draft:
https://github.com/IBM/unitxt/pull/478

**Pull request closed without merging**
