### PR TITLE
revived no_deep just to compare performance

### PR DESCRIPTION
**Pull request by dafnapension**

### CODE REVIEW

**Comment by dafnapension** [comment]
Performance profiling of `cards/cola.json`  non-eager mode  (see details in PR #1255 )

image

**Comment by dafnapension** [comment]
And now cola in eager mode:

image

**Comment by dafnapension** [comment]
And the same for `examples/evaluate_a_judge_model_capabilities_on_arena_hard.py`, non-eager first:

image

**Comment by dafnapension** [comment]
And finally, the above example in eager mode:

image

**Review by elronbandel — APPROVED** [review]
AMAZING WORK.

**Pull request merged**
