### PR TITLE
Add few public datasets cards from IBM internal fmeval project

### PR DESCRIPTION
**Pull request by OfirArviv**

### CODE REVIEW

**Review by elronbandel — CHANGES_REQUESTED** [review]
it has to be with relative imports 
from unitxt.blocks -> from src.unitxt.blocks

**Comment by OfirArviv** [comment]
> it has to be with relative imports from unitxt.blocks -> from src.unitxt.blocks

oh sorry. I copied-paste it and didn't notice :)

**Comment by OfirArviv** [comment]
@elronbandel toxin require hugginface token for accepting its term. Can you add it? Otherwise we will get an error in the tests.

`datasets.exceptions.DatasetNotFoundError: Dataset 'skg/toxigen-data' doesn't exist on the Hub. If the repo is private or gated, make sure to log in with `huggingface-cli login`. `

**Comment by elronbandel** [comment]
@OfirArviv Lets get rid of earning calls dataset for now, wdyt?

**Comment by OfirArviv** [comment]
> @OfirArviv Lets get rid of earning calls dataset for now, wdyt?

ahead of you :)

**Review by elronbandel — APPROVED** [review]

**Pull request merged**
