### PR TITLE
saving prediction-references and restore within PipelineMetric (including rag), allows to remove the deep copy from within ApplyMetric, and InstanceFieldOperator

### PR DESCRIPTION
**Pull request by dafnapension**

### CODE REVIEW

**Comment by elronbandel** [comment]
What is the purpose? the issue with deep copy?

**Comment by dafnapension** [comment]
Just to discipline metric.  No metric should be allowed to change prediction or references.

What is the problem with rag? Not that it changes prediction and references?

**Comment by elronbandel** [comment]
Could you investigate it? I think that's part of the problem there

**Comment by dafnapension** [comment]
Hi @elronbandel , please write a small piece of code for me that demonstrates that something is wrong in the current status.  Where is the current status? Why did you refer me to the PR of Binyamin?  Is he trying to do something related to main? Does the problem show in main too?

**Review by elronbandel — CHANGES_REQUESTED** [review]
Instead of requiring developers for adopting to this mechanism could we just do it behind the scenes in the PipelineMetric internal code?

**Pull request closed without merging**
