### PR TITLE
Add Capitalize and Substring operators.  Add tests.

### LINKED ISSUE #608: Add Capitalize and Substring operators
I need new string operators for an fm-eval test.

### PR DESCRIPTION
**Pull request by jlqibm**
This adds more string processors.
Closes #608 .

### CODE REVIEW

**Review by elronbandel — APPROVED** [review]

**Review by elronbandel — CHANGES_REQUESTED** [review]
The tests are failing because the catalog files (json files created when you run add_to_catalog) are missing.  Add them to the pr. Then make sure to run `make pre-commit` before commiting any more changes to verify the code quality and security. 
@jlqibm

**Comment by jlqibm** [comment]
@elronbandel Missing catalog files are added now to the fork

**Comment by elronbandel** [comment]
Yet the formatting is not good. Can you run 'make format' and check it works smoothly?

**Comment by jlqibm** [comment]
@elronbandel test_postprocessors.py got reformatted.  I've pushed it to my fork.

**Review by elronbandel — APPROVED** [review]

**Pull request merged**
