### PR TITLE
Add a test for sentence-bert based answer correctness metrics

### PR DESCRIPTION
**Pull request by matanor**

### CODE REVIEW

**Comment by dafnapension** [comment]
Hi @matanor , I thought that `tetst_metrics.py` should be fixed. Is this PR in reference to issue https://github.com/IBM/unitxt/issues/1136 that I assigned to you (because your name shows in gitlens..)?

**Comment by matanor** [comment]
> Hi @matanor , I thought that `tetst_metrics.py` should be fixed. Is this PR in reference to issue #1136 that I assigned to you (because your name shows in gitlens.. as the one who moved the tests from prepare to test_metrics)?

hi @dafnapension ! you mean we should first fix the above issue, before considering this PR ? (though the issue is on `context_correctness`, here its about new tests for `answer_correctness`)

**Comment by dafnapension** [comment]
I must admit that I am less familiar with the exact inference power of the different models, I participate in unitxt more on the level of "pattern recognition" of code issues: if I see a problem (like [this issue](https://github.com/IBM/unitxt/issues/1136)), or asked to help with some specific pieces of code.
I only have my own Win10 machine (running on Dell), no access to any GPU.
So in these terms (of סדר וניקיון) I bumped into this [issue](https://github.com/IBM/unitxt/issues/1136), and looked in gitlens to see who can understand what is going on, and found your name in gitlens.
Now you explained in the PR (that made your name show in gitlens) that you see value in moving tests from prepare to `test_metrics`.
So now, in terms of סדר וניקיון, even before the correctness of the scores..  I am puzzled about two issues:
(1) why heavy tests again in prepare, and not in test_metrics,
(2) what about this "def text_context_correctness(self):"  (note the  text_...   which prevents this method from being tested at all) that I had the impression that is related to your current PR.

**Comment by dafnapension** [comment]
Hi @matanor , this is how I manage to run your `prepare/metrics/rag_answer_correctness.py`  on my little Dell:

image

**Review by dafnapension — APPROVED** [review]

**Comment by matanor** [comment]
@dafnapension same question as [here](https://github.com/IBM/unitxt/pull/1143#issuecomment-2286475422) .. is it ok to merge?
the error in `Test Catalog Preparation` seemd unrelated?

**Comment by dafnapension** [comment]
Yes yes, from my perspective. I suspect, though that the 'merge' button is not applicable without passing all automatic tests.

**Pull request merged**
