### PR TITLE
Create tasks_taxonomy

### PR DESCRIPTION
**Pull request by gitMichal**
wip.. 
taxonomy definition

### CODE REVIEW

**Review by borgr — COMMENTED** [review]
We differentiate open QA from multiple choice but not abstractive and extractive and not regular from multihop? (This makes sense to me, as the templates might be the same. So the distinction just helps finding the task but have little practical value)
Also closed book must have their own sub category. 
What about no answer? It is probably shown in the templates, but should it define the category somehow?
Same for summarization abstractive and extractive?
Summarization as you know is just very ill-defined but a lot could be changed there as well (headline generation simplification etc.).
what unifies the different text generations? What is MT and summarization not under it?

**Review by borgr — COMMENTED** [review]
Also, what about regression? (ranking and clustering I guess are just very rare tasks in NLP outputs)

**Comment by gitMichal** [comment]
> We differentiate open QA from multiple choice but not abstractive and extractive and not regular from multihop? (This makes sense to me, as the templates might be the same. So the distinction just helps finding the task but have little practical value) Also closed book must have their own sub category. What about no answer? It is probably shown in the templates, but should it define the category somehow? Same for summarization abstractive and extractive? Summarization as you know is just very ill-defined but a lot could be changed there as well (headline generation simplification etc.). what unifies the different text generations? What is MT and summarization not under it?

thanks @borgr , will try to address some of the issues you raised..
- indeed "no answer" is somehow encoded in some of the templates. If you think it deserves a category by itself, we should consider.
- for summarization i think that extractive is (almost) no longer in the game... and thus wonder if we should create such a sub-category
- MT- machine translation 
- about text generation.. i agree that another taxonomy could be NLG, NLU and then to put under NLG summarization.. but again we need to stick to something..

**Comment by gitMichal** [comment]
i did few more changes. @borgr please take a looks and feel free to modify

**Comment by yoavkatz** [comment]
Can we close this?

**Comment by yoavkatz** [comment]
Closing as I assume it's no longer needed.

**Pull request closed without merging**
