### PR TITLE
separating rag metrics and adding bge metrics - catalog non backward compatible change

### PR DESCRIPTION
**Pull request by assaftibm**
I reorganized some of the rag metrics, now we have:

For `context correctness`:
```
metrics.rag.context_correctness
metrics.rag.context_correctness/map
metrics.rag.context_correctness/mrr
metrics.rag.context_correctness/retrieval_at_k
```

For `context relevance`:
```
metrics.rag.context_relevance
metrics.rag.context_relevance/perplexity
metrics.rag.context_relevance/sentence_bert
```

For `faithfulness`:
```
metrics.rag.faithfulness
metrics.rag.faithfulness.token_k_precision
metrics.rag.faithfulness.bert_score_k_precision
metrics.rag.faithfulness.bert_score_k_precision_ml
metrics.rag.faithfulness.sentence_bert
```

For `answer correctness`:
```
metrics.rag.answer_correctness
metrics.rag.answer_correctness.token_recall
metrics.rag.answer_correctness.bert_score_recall
metrics.rag.answer_correctness.bert_score_recall_ml
metrics.rag.answer_correctness.sentence_bert
```

Some of these were originally in a different location / name - listed in gray below:

Also added the sentence bert metric with BGE large 1.5 to catalog.
image

### CODE REVIEW

**Comment by assaftibm** [comment]
I reorganized some of the rag metrics, now we have:
For `context relevance`:
```
metrics.rag.context_relevance
metrics.rag.context_relevance/perplexity
metrics.rag.context_relevance/sentence_bert
```

For `faithfulness`:
```
metrics.rag.faithfulness
metrics.rag.faithfulness.token_k_precision
metrics.rag.faithfulness.bert_score_k_precision
metrics.rag.faithfulness.bert_score_k_precision_ml
metrics.rag.faithfulness.sentence_bert
```

For `answer correctness`:
```
metrics.rag.answer_correctness
metrics.rag.answer_correctness.token_recall
metrics.rag.answer_correctness.bert_score_recall
metrics.rag.answer_correctness.bert_score_recall_ml
metrics.rag.answer_correctness.sentence_bert
```

Some of these were originally in a different location / name - listed in gray below:
image

Also added the sentence bert metric with BGE large 1.5 to catalog.

**Comment by assaftibm** [comment]
I'm not sure what this error means - 
```
{'file': '/home/runner/work/unitxt/unitxt/src/unitxt/catalog/metrics/rag/answer_correctness/sentence_bert.json', 'diff': 'old only'}
{'file': '/home/runner/work/unitxt/unitxt/src/unitxt/catalog/metrics/rag/context_perplexity.json', 'diff': 'old only'}
{'file': '/home/runner/work/unitxt/unitxt/src/unitxt/catalog/metrics/rag/context_relevance/sentence_bert.json', 'diff': 'old only'}
{'file': '/home/runner/work/unitxt/unitxt/src/unitxt/catalog/metrics/rag/faithfulness/sentence_bert.json', 'diff': 'old only'}
```
The `sentence_bert.json` files are new
The `context_perplexity.json` hasn't changed.

**Comment by assaftibm** [comment]
I din't understand any of the CI/CD errors.

**Comment by yoavkatz** [comment]
> I'm not sure what this error means -
> 
> ```
> {'file': '/home/runner/work/unitxt/unitxt/src/unitxt/catalog/metrics/rag/answer_correctness/sentence_bert.json', 'diff': 'old only'}
> {'file': '/home/runner/work/unitxt/unitxt/src/unitxt/catalog/metrics/rag/context_perplexity.json', 'diff': 'old only'}
> {'file': '/home/runner/work/unitxt/unitxt/src/unitxt/catalog/metrics/rag/context_relevance/sentence_bert.json', 'diff': 'old only'}
> {'file': '/home/runner/work/unitxt/unitxt/src/unitxt/catalog/metrics/rag/faithfulness/sentence_bert.json', 'diff': 'old only'}
> ```
> 
> The `sentence_bert.json` files are new The `context_perplexity.json` hasn't changed.

What this means is that if we delete all the json files in the catalog and regenerate them fton the prepare python files, these 4  files  are not generated.

**Comment by assaftibm** [comment]
Thanks, all pass now except for `Test HELM Integration / test-helm`

**Review by yoavkatz — APPROVED** [review]

**Comment by yoavkatz** [comment]
Do you want to change it from Draft?

**Comment by assaftibm** [comment]
finished the reorg of another metric  (context correctness) and removed the draft status.

**Review by yoavkatz — APPROVED** [review]

**Pull request merged**
