### PR TITLE
Fix broken test_operator

### LINKED ISSUE #255: example operator test is broken
Trying to add the new operator in the docs gives an assertion error.  The test on line 42 in test_utils/operators.py is backwards.

```
(fme) [jlquinn@cccxl005 unitxt]$ python ../optest.py 
/u/jlquinn/jlquinn-mt/gaama/conda.x86/envs/fme/lib/python3.9/site-packages/torch/cuda/__init__.py:546: UserWarning: Can't initialize NVML
  warnings.warn("Can't initialize NVML")
Artifact tmp_name saved to /tmp/tmpoyx56n6a/tmp_name.json
Traceback (most recent call last):
  File "/dccstor/multilm2/fm-ml-foglight/unitxt/../optest.py", line 29, in <module>
    print(test_operator(operator, inputs, targets)) # True
  File "/dccstor/multilm2/fm-ml-foglight/unitxt/src/unitxt/test_utils/operators.py", line 46, in test_operator
    raise AssertionError("\n".join(errors))
AssertionError: input and output must be equal, got <{'a': 1, 'b': 2}> =/= <{'a': 1, 'b': 2}>
input and output must be equal, got <{'a': 2, 'b': 2}> =/= <{'a': 2, 'b': 2}>

```


optest.py

```
from typing import (                                                                                                                                                                                 
    Any,                                                                                                                                                                                             
    Callable,                                                                                                                                                                                        
    Dict,                                                                                                                                                                                            
    Generator,                                                                                                                                                                                       
    Iterable,                                                                                                                                                                                        
    List,                                                                                                                                                                                            
    Optional,                                                                                                                                                                                        
    Tuple,                                                                                                                                                                                           
    Union,                                                                                                                                                                                           
)                                                                                                                                                                                                    
from unitxt.operator import StreamInstanceOperator                                                                                                                                                   
                                                                                                                                                                                                     
class AddFields1(StreamInstanceOperator):                                                                                                                                                            
    fields: Dict[str, object]                                                                                                                                                                        
                                                                                                                                                                                                     
    def process(self, instance: Dict[str, Any], stream_name: str = None) -> Dict[str, Any]:                                                                                                          
        return {**instance, **self.fields}                                                                                                                                                           
                                                                                                                                                                                                     
                                                                                                                                                                                                     
operator = AddFields1(fields={"b": 2})                                                                                                                                                               
                                                                                                                                                                                                     
inputs = [{'a': 1}, {'a': 2}]                                                                                                                                                                        
targets = [{'a': 1, 'b': 2}, {'a': 2, 'b': 2}]                                                                                                                                                       
                                                                                                                                                                                                     
from unitxt.test_utils.operators import test_operator                                                                                                                                                
                                                                                                                                                                                                     
print(test_operator(operator, inputs, targets)) # True                                                                                                                                               
```

### PR DESCRIPTION
**Pull request by jlqibm**
Fixes #255

### CODE REVIEW

**Comment by yoavkatz** [comment]
Thanks for the catch.  I think all other uses  provider the tester object, so the code was not run.

You need to recommit code with Sign Off - to pass the DCO tests.

**Comment by jlqibm** [comment]
@yoavkatz Did I need the gpg signature?  Or the signoff feature of git?

**Comment by yoavkatz** [comment]
It should be the signoff feature of git.  I can approve the exception.

**Review by yoavkatz — APPROVED** [review]

**Comment by yoavkatz** [comment]
There is missing coverage, so I can not merge the change.  Can you make the change in a branch of this repository, so I can continue to work on it.  ( Or I can make it in a new branch).

**Comment by jlqibm** [comment]
@yoavkatz do I have permissions to create a branch on this repo?

**Comment by yoavkatz** [comment]
You should have access, after you accept the invite:

image

However, I created a new branch and PR (#275 ) that fixes the issue and adds a test.

**Pull request closed without merging**
