### PR TITLE
change CopyFields operators name to Copy

### PR DESCRIPTION
**Pull request by duckling69**
This partially solves #840 

All tests seems to pass 
image

### CODE REVIEW

**Comment by duckling69** [comment]
can you please review // @elronbandel

**Review by elronbandel — CHANGES_REQUESTED** [review]
Great work @duckling69!

To pass the consistency test you will need to recompile all the catalog by running: `python utils/prepare_all_artifacts.py` abit annoying but necassry (should take few minutes max). Than commit all the catalog json that has changed.

Also make sure again there are no new `CopyFields` so we can merge this asap

**Comment by duckling69** [comment]
@elronbandel i did the reviewed changes

**Review by elronbandel — APPROVED** [review]
Amazing job! thanks for the contribution!!! Let me know if you want to do any more (like RenameFields and others)

**Comment by duckling69** [comment]
> Amazing job! thanks for the contribution!!! Let me know if you want to do any more (like RenameFields and others)

sure anything i can help with 🙌

**Pull request merged**
