### PR TITLE
added take_first_non_empty_line

### PR DESCRIPTION
**Pull request by gitMichal**
@matanor please review, i added the postprocessor in YesNo and other classifications

### CODE REVIEW

**Review by matanor — APPROVED** [review]
LGTM

**Review by yoavkatz — APPROVED** [review]

**Review by yoavkatz — CHANGES_REQUESTED** [review]
You also need to regenerate the json cards.

**Comment by yoavkatz** [comment]
@gitMichal this needs to be merged with main.  So changes were already there.

**Comment by yoavkatz** [comment]
Not relevant any more.

**Pull request closed without merging**
