### PR TITLE
Extend the function that evaluate with unitxt metric on external data to new types of data

### PR DESCRIPTION
**Pull request by assaftibm**

### CODE REVIEW

**Review by elronbandel — CHANGES_REQUESTED** [review]
Can you explain here what is the purpose of this? also maybe add comment in the code? I think singledispatch s not very common and wont be clear to everyone what you did

**Comment by assaftibm** [comment]
The idea was to overload the "evaluate" function with two different implementations - one that takes a dataframe and the other takes a list of dicts. This overloading can be implemented in different ways, if you prefer something specific I can change.

**Comment by assaftibm** [comment]
This is the formal doc with example - https://docs.python.org/3/library/functools.html#functools.singledispatch

**Comment by assaftibm** [comment]
I added a comment

**Review by elronbandel — APPROVED** [review]

**Pull request merged**
